name: user_management
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # http
  http: ^1.3.0
  
  #state management
  get: ^4.6.6
  provider: ^6.0.5
  get_storage: ^2.1.1

  # font
  google_fonts: ^6.2.1

  # icon
  iconsax: ^0.0.8

  # animation
  loading_animation_widget: ^1.3.0

  # utils
  flutter_svg: ^2.0.6
 
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
